export const ROUTES = {
  HOME: "/",
  ABOUT: "/about",
  CONTACT: "/contact",
  LOGIN: "/login",
  REGISTER: "/register",
  PORTFOLIO: "/portfolio",
  HOW_IT_WORKS: "/how-it-works",
  OUR_SERVICES: "/our-services",
  PRICING: "/pricing",
  BLOGS: "/blog",
  BLOG_DETAILS: "/blog/:blogId",
  SERVICE_DETAILS: "/services/:serviceId",
  PRIVACY: "/privacy-policy",
  SEARCH: "/search",
};
