export const ROUTES = {
  HOME: "/",
  ABOUT: "/about",
  CONTACT: "/contact",
  LOGIN: "/login",
  REGISTER: "/register",
  DATA_FORM: "/register/details",
  PORTFOLIO: "/portfolio",
  HOW_IT_WORKS: "/how-it-works",
  PRICING: "/pricing",
  BLOGS: "/blog",
  BLOG_DETAILS: "/blog/:blogId",
  SERVICE_DETAILS: "/services/:serviceId",
  PRIVACY: "/privacy-policy",
};
